version: '3.8'

services:
  driver-availability-service:
    build:
      context: ./driver_availability_service
    ports:
      - "5002:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:admin@db:5432/test
      - SECRET_KEY=my_secret_key
      - JWT_SECRET_KEY=abcdefgh1234567890

  # other services

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
