version: '3.8'

services:
  booking-service:
    build:
      context: ./booking-service
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:admin@db:5432/test
      - SECRET_KEY=my_secret_key
      - JWT_SECRET_KEY=abcdefgh1234567890
    depends_on:
      - db

  user-management-service:
    build:
      context: ./user-management-service
    ports:
      - "5002:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:admin@db:5432/test
      - SECRET_KEY=my_secret_key
      - JWT_SECRET_KEY=abcdefgh1234567890
    depends_on:
      - db
      
  driver-availability-service:
    build:
      context: ./driver_availability_service
    ports:
      - "5003:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:admin@db:5432/test
      - SECRET_KEY=my_secret_key
      - JWT_SECRET_KEY=abcdefgh1234567890
    depends_on:
      - db

  route-management-service:
    build:
      context: ./route_management_service
    ports:
      - "5004:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:admin@db:5432/test
      - SECRET_KEY=my_secret_key
      - JWT_SECRET_KEY=abcdefgh1234567890
    depends_on:
      - db

  admin_management_service:
    build: ./admin_management_service
    ports:
      - "5005:5000"
    environment:
      - SECRET_KEY=my_secret_key
      - DATABASE_URL=postgresql://postgres:admin@db:5432/test
      - JWT_SECRET_KEY=abcdefgh1234567890
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=raju0518@gmail.com
      - MAIL_PASSWORD=ramaraju0518
      - MAIL_USE_TLS=True
      - MAIL_USE_SSL=False
    depends_on:
      - db
  
  celery_worker:
    build: ./cron_jobs_service
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:admin@db:5432/test
    depends_on:
      - redis
      - db

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
